import turtle
turtle.reset()
turtle.shape("turtle")
turtle.pencolor("#15adaa")
turtle.pensize(5)
turtle.begin_fill()
turtle.fillcolor("#15adaa")
turtle.circle(50)
turtle.end_fill()
turtle.pencolor("green")
turtle.lt(180)
turtle.circle(100)
turtle.rt(90)
turtle.penup()     
turtle.fd(100)
turtle.pendown()
turtle.pencolor("red")
turtle.lt(-90)
turtle.circle(25)

turtle.mainloop()
